config/routes.rb
Rails.application.routes.draw do
  root 'pages#top'

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	# 一覧用
  	@books = Book.all

  	# 新規登録用
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])

  	if @book.update(book_params)
		flash[:success] = "Book was successfully updated."
	  	redirect_to @book
	else
		render :edit
	end
  end

  def create
  	@book = Book.new(book_params)
  	@books = Book.all

  	if @book.save
		flash[:success] = "Book was successfully created."
	  	redirect_to @book
	else
		render :index
	end

  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
	flash[:success] = "Book was successfully destroyed."
  	redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<%= render 'form', book: @book %>

<h1>Editing Book</h1>

<%= form_for @book do |f| %>
  <div class="field">
	<%= f.label :title %>
	<%= f.text_field :title %>
  </div>
  <div class="field">
	<%= f.label :body %>
	<%= f.text_area :body %>
  </div>

  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |f| %>
    <tr>
      <td><%= f.title %></td>
      <td><%= f.body %></td>
      <td><%= link_to "show", book_path(f.id) %></td>
      <td><%= link_to "edit", edit_book_path(f.id) %></td>
      <td><%= link_to "destroy", book_path(f.id), method: :delete, data: { confirm: 'Are you sure ?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>

<%= render 'form', book: @book %>

<%= form_for @book do |f| %>
  <div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label for="book_title">Body</label>
    <%= f.text_area :body %>
  </div>
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/new.html.erb
<%= form_for(@blog) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_field :body %>

    <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<p><strong>Title:</strong> <%= @book.title %></p>
<p><strong>Body:</strong> <%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book) %> | <%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <p><%= message %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><%= link_to "start", books_path %></p>
</body>